apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: danielj4mv/streamlit:latest
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  ports:
  - port: 8087
    targetPort: 8087
    nodePort: 30001
  selector:
    app: streamlit-app
